# .bash_profile

# Get the aliases and functions

if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

# Get machine specific environment

if [ -f ~/.$(hostname)_profile ]; then
	. ~/.$(hostname)_profile
fi

# This env variable is used by racer

export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src
