# .bashrc
# this file is for aliases and functions

# my beloved locale settings
export LANG="en_GB.utf8"
export LC_MONETARY="pl_PL.utf8"
export LC_PAPER="pl_PL.utf8"
export LC_NAME="pl_PL.utf8"
export LC_ADDRESS="pl_PL.utf8"
export LC_TELEPHONE="pl_PL.utf8"
export LC_MEASUREMENT="pl_PL.utf8"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# == user specific aliases and functions ==================

alias grep="grep --color"
alias egrep="egrep --color"

export SVN_EDITOR=vim

export EDITOR=vim

# == stuff that came from Arch ============================

alias ls='ls --color=always'

git_branch () {
	local branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
	if [ -n "$branch" ]; then
		echo -n "  "
		# echo -n $branch | sed -e "s|\(.\)[^/]*/|\1/|g"
		echo -n $branch
	fi
}
PS1='[\u@\h \W$(git_branch)]\$ '

# == Fedora has this by default, yet noone else do ========
alias cd..='cd ..'
alias ll='ls -l'
alias la='ls -A'
alias dir='exa'
alias dl='exa -l --git'
alias ssh='ssh -X'
alias yum='dnf'
alias vim='vimx' # normal vim does not have X clipboard support enabled
alias ocaml='rlwrap ocaml' # stupid ocaml
alias ps='ps --forest'
alias cls='clear'

# Rust env, this should be in bash_profile:
if [ -f ~/.cargo/env ]; then
	source "$HOME/.cargo/env"
fi

# Gtk VTE reads additional infro from vte.sh
# https://gnunn1.github.io/tilix-web/manual/vteconfig/
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
