" == Vundle configuration ============================================

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" Keep Plugin commands between vundle#begin/end.
call vundle#begin()

Plugin 'VundleVim/Vundle.vim' " let Vundle manage Vundle, required
Plugin 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-scripts/a.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'dreamer/mustang-vim'

call vundle#end()            " required

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to
"                     auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" == Powerline configuration =========================================
"
" Always show statusline
set laststatus=2


" == Vim configuration ===============================================
"
" this is needed, so we can use any char for listchars
scriptencoding utf-8
set encoding=utf-8

" covert tabs to 4 spaces
"set shiftwidth=4
"set tabstop=4
set nu
set nowrap
set nostartofline
set t_Co=256

" Change invisible characters
set listchars=tab:»\ ,trail:·,eol:↲

" Clear selection with ,/
nmap <silent> ,/ :let @/=""<CR>

" Default yank register is same as system clipboard
set clipboard=unnamedplus

" Unbind usual keys
" h
map <silent><Left>  <Esc>
" j
map <silent><Down>  <Esc>
" k
map <silent><Up>    <Esc>
" l
map <silent><Right> <Esc>
" Ctrl D
map <silent><PageDown>  <Esc>
" Ctrl U
map <silent><PageUp>    <Esc>
" 0
map <silent><Home>      <Esc>
" $
map <silent><End>       <Esc>

colorscheme mustang

" this hack fixes background rendering for mustang
if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  set t_ut=
endif

" set syntax for .gitconfig .git/config gerrit's project.config etc…
autocmd BufRead,BufNewFile *config set filetype=dosini

