#!/bin/bash

for p in plugins/*.bash ; do source $p ; done

install_vimrc
install_nvimrc

force_link_file	$(pwd)/dotfiles/bashrc		~/.bashrc
force_link_file	$(pwd)/dotfiles/bash_profile	~/.bash_profile

#link_file	$(pwd)/dotfiles/terminator	~/.config/terminator/config
link_file	$(pwd)/dotfiles/gvimrc		~/.gvimrc
link_file	$(pwd)/dotfiles/gitconfig	~/.gitconfig
link_file	$(pwd)/dotfiles/gitignore	~/.gitignore

for s in scripts/* ; do
	link_file	$(pwd)/$s		~/bin/$(basename $s)
done

change_gnome_defaults
change_tilix_defaults

download_fonts
