#!/bin/bash

for p in plugins/*.bash ; do
	source $p
done

install_rpmfusion
install_packages my-fedora-rpms

link_dropbox	~/Dropbox/Documents		~/Documents
link_dropbox	~/Dropbox/Pictures		~/Pictures
link_dropbox	~/Dropbox/Public		~/Public
link_dropbox	~/Dropbox/home/Templates	~/Templates
