#!/bin/bash

source plugins/dropbox.bash
source plugins/rpmfusion.bash

install_rpmfusion

link_dropbox	~/Dropbox/Documents		~/Documents
link_dropbox	~/Dropbox/Pictures		~/Pictures
link_dropbox	~/Dropbox/Public		~/Public
link_dropbox	~/Dropbox/home/Templates	~/Templates
